apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: rackspace-system
  labels:
    k8s-app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
