apiVersion: v1
kind: Service
metadata:
  name: ingress-controller
  labels:
    k8s-app: ingress-controller
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    protocol: TCP
    targetPort: 80
    name: http
  - port: 443
    nodePort: 30443
    protocol: TCP
    targetPort: 443
    name: https
  selector:
    k8s-app: ingress-controller
