apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: es-exporter
  namespace: rackspace-monitoring
  labels:
    monitor: rackspace-prometheus 
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: es-exporter
  namespaceSelector:
    matchNames:
    - rackspace-system
  endpoints:
  - port: http-metrics
    interval: 15s